spring.application.name=hospitalManagement
server.servlet.context-path=/api/v1
server.shutdown=immediate

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb2?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql